apiVersion: v1
kind: Service
metadata:
  name: amqp-api-service
  labels:
    version: 0.0.2
spec:
  selector:
    app: amqp-api-deployment
  ports:
  - name: http-port
    protocol: TCP
    port: 2500
    targetPort: 2500
    nodePort: 32300
  type: NodePort