apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mytestcontainer-deployment
  name: mytestcontainer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytestcontainer-deployment
  template:
    metadata:
      labels:
        app: mytestcontainer-deployment
    spec:
      containers:
      - image: toszo/mytestcontainer:0.0.1
        name: mytestcontainer
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
